# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: "http://agalite.test"
  host: "agalite.test"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:

    - "src/**/*"
    - "!src/{images,images/**/*,js,js/**/*,scss,scss/**/*}"
    #- "src/favicons/**/*"
    #- "!node_modules/slick-carousel/slick/{*.*}"
    #- "node_modules/font-awesome/**/*"
    #- "!node_modules/font-awesome/{*.txt,*.json,*.md,css,css,less,less/**/*,scss,scss/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    #- "node_modules/foundation-sites/scss"
    #- "node_modules/motion-ui/src"
    #- "node_modules/slick-carousel/slick/"
    #- "node_modules/font-awesome/scss"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/app.js"
    - "src/js/bootstrap.min.js"
    - "src/js/modernizr.min.js"
    #- "src/js/jquery-3.4.1.min.js"
    #- "src/js/jquery.unveil.js"
  # Paths for the package task to include/exclude in .zip archive
  package:
    - "**/*"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/codesniffer.ruleset.xml"
    - "!**/composer.json"
    - "!**/composer.lock"
    - "!**/config.yml"
    - "!**/config.default.yml"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"
    - "!**/webpack.config.js"
  # Paths for PHP CodeSniffer
  phpcs:
    - "**/*.php"
    - "!wpcs"
    - "!wpcs/**"
